"""Add file_type column to PDFs table

Revision ID: ac1a7704265c
Revises: c58a0c5996f8
Create Date: 2025-07-04 21:28:42.930089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1a7704265c'
down_revision: Union[str, None] = 'c58a0c5996f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdfs', 'file_type')
    # ### end Alembic commands ###
