"""add page counters to pdf

Revision ID: c58a0c5996f8
Revises: 
Create Date: 2025-04-16 01:02:06.658845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58a0c5996f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('pages_total', sa.Integer(), nullable=True))
    op.add_column('pdfs', sa.Column('pages_indexed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdfs', 'pages_indexed')
    op.drop_column('pdfs', 'pages_total')
    # ### end Alembic commands ###
